CREATE TABLE PESSOA (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
CPF VARCHAR(11),
RG VARCHAR(20),
SEXO VARCHAR(10),
CEP VARCHAR(10),
RUA VARCHAR(60),
NUMERO VARCHAR(10),
BAIRRO VARCHAR(60),
COMP VARCHAR(150),
CIDADE VARCHAR(60),
UF VARCHAR(4)
);

CREATE TABLE PRODUTO (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR(100),
PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
CLIENTE_ID INTEGER REFERENCES PESSOA (ID),
DATA_PEDIDO TIMESTAMP,
STATUS VARCHAR(20),
TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
QUANTIDADE INTEGER
);


CREATE TABLE USUARIO (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(50),
PASSWORD VARCHAR(180),
ADMIN boolean
);



